// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { getSupabaseConfig } from '@/lib/config';

const cfg = getSupabaseConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let client: any = undefined;
if (cfg.url && cfg.anonKey) {
  client = createClient(cfg.url, cfg.anonKey, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
} else {
  console.warn('[Config] Supabase URL/anon key missing. Open /setup to configure.');
}

export const supabase = client;